name: pytorch_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - numba
  - defaults
dependencies:
  - pytorch
  - pytorch-cuda=12.4
  - torchaudio
  - torchvision
  - gdal
  - conda-forge::tqdm
  - matplotlib
  - scipy
  - scikit-image
  - numba::numba