name: lambda_pnn_env
channels:
  - defaults
dependencies:
  - numpy
  - cudatoolkit
  - gdal
  - scikit-image
  - scipy
  - tqdm
  - scikit-learn
  - matplotlib
  - h5py
  - numba
  - tensorboardx
  - opencv
  - pytorch-cuda=11.8
  - pytorch
  - torchaudio
  - torchvision
